### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by calren** [jdelgado111/SimpleTweet#1]
Awesome job getting all the required features and some of the optionals!! The optionals this week are definitely more challenging than usual (especially that infinite pagination one...), but I'm really glad that you had some time to explore them and give them a try.

In case you missed it, we have a new guide on implementing infinite pagination https://hackmd.io/s/ryGzehmE4 . Feel free to give that a try if you have some extra time this week! And we're always open to help troubleshoot issues if you need it.

Keep up the great work :)

**Comment by codepathreview** [comment]
Twitter app looking amazing! Love the UI polish you were able to add in. 
/cc @codepathreview
